language: erlang
otp_release:
  - 17.1
sudo: false
env:
  - MIX_ENV=test
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.2.zip
  - unzip -d elixir v1.0.2.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - cp config/test.travis.exs config/test.exs
  - mix local.hex --force
  - mix deps.get --only test
  - psql -c 'create database phoenix_crud;' -U postgres
  - mix ecto.migrate PhoenixCrud.Repo
script: mix test
